### ISSUE TITLE
Unraid使用docker部署访问页面显示message:unauthorized

### ISSUE THREAD

**Issue by bravoleexin** [xjasonlyu/jellyfin-plugin-avdc#10]
拉取的dockerhub镜像，没有添加pwd，运行成功后显示message:unauthorized

**Comment by xjasonlyu** [comment]
你設置token了嘛

**Comment by bravoleexin** [comment]
> 
> 
> 你設置token了嘛

password 
变量里面除了pwd其他都有按照设置

**Comment by xjasonlyu** [comment]
你把docker配置的具體參數給我看看

**Comment by bravoleexin** [comment]
> 
> 
> 你把docker配置的具體參數給我看看

晚上回复给您，谢谢大佬。
另外，我回忆了一下，访问页面具体显示的是 {"message":"unauthorized","status":false}。
我配置文件里设置的局域网PC的http代理，使用的是v2rayN开启了局域网共享，这个确信没问题。但是jellyfin里使用avdc刮削时，在pc的v2rayN上看不到相关数据请求。

**Comment by xjasonlyu** [comment]
如果你設置了ACDV_TOKEN的話，顯示unauthorized 是正常的，因為需要在avdc plugin裡設置token才能正常訪問。

v2rayN看不到數據請求可能跟設置有關也可能沒走代理，也可能是avdc直接用了數據庫的數據。

**Comment by bravoleexin** [comment]
> 
> 
> 如果你設置了ACDV_TOKEN的話，顯示unauthorized 是正常的，因為需要在avdc plugin裡設置token才能正常訪問。
> 
> v2rayN看不到數據請求可能跟設置有關也可能沒走代理，也可能是avdc直接用了數據庫的數據。

我重新部署了一下发现元数据可以刮削了，但是没有图片，于是我单个影片进行元数据更新发现可以完美刮削，图片正常。和隔壁的issue一样的问题。另附日志：
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/app/server/views.py", line 79, in _actress_image
actress = api.GetActressByName(name)
File "/app/server/api.py", line 152, in GetActressByName
actress = db_api.GetActressByName(name)
File "/app/server/db_api.py", line 32, in GetActressByName
result: Actresses = Actresses.get((Actresses.name == name))
File "/usr/local/lib/python3.9/site-packages/peewee.py", line 6438, in get
return sq.get()
File "/usr/local/lib/python3.9/site-packages/peewee.py", line 6884, in get
return clone.execute(database)[0]
File "/usr/local/lib/python3.9/site-packages/peewee.py", line 1907, in inner
return method(self, database, *args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/peewee.py", line 1978, in execute
return self._execute(database)
File "/usr/local/lib/python3.9/site-packages/peewee.py", line 2150, in _execute
cursor = database.execute(self)
File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3157, in execute
return self.execute_sql(sql, params, commit=commit)
File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3151, in execute_sql
self.commit()
File "/usr/local/lib/python3.9/site-packages/peewee.py", line 2917, in __exit__
reraise(new_type, new_type(exc_value, *exc_args), traceback)
File "/usr/local/lib/python3.9/site-packages/peewee.py", line 190, in reraise
raise value.with_traceback(tb)
File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3142, in execute_sql
cursor = self.cursor(commit)
File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3129, in cursor
return self._state.conn.cursor()
peewee.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 23143287019264 and this is thread id 23143244470016.
172.17.0.1 - - [08/Apr/2021 20:30:30] "[35m[1mGET /image/actress/三上悠亜/0 HTTP/1.1[0m" 500 -
172.17.0.1 - - [08/Apr/2021 20:30:31] "[37mGET /image/actress/葵つかさ/0 HTTP/1.1[0m" 200 -
172.17.0.1 - - [08/Apr/2021 20:30:31] "[37mGET /image/primary/SSNI-744 HTTP/1.1[0m" 200 -
[2021-04-08 20:30:31,185] ERROR in app: Exception on /image/thumb/SSNI-744 [GET]

最后一行时红色错误提示，每一部影片都是这样的。操作是在媒体库点击扫描文件并点选更新全部元数据。

**Comment by xjasonlyu** [comment]
你重新拉一下镜像试试

**Comment by bravoleexin** [comment]
> 
> 
> 你重新拉一下镜像试试

问题消失，完美刮削，日志无错误。感谢辛苦修改~

**Comment by lovelively** [comment]
您好，能讲解一下这个http代理设置的问题吗，小白实在太难了，我有软路由环境，那个http代理应该如何填呢

**Comment by xjasonlyu** [comment]
一般任何科學上網的插件/軟件都會提供http代理接入的啊

**Comment by lovelively** [comment]
> 一般任何科學上網的插件 / 軟件都會提供 http 代理接入的啊

请问您指的是插件里面的服务端吗？是这个吗？
![image](https://user-images.githubusercontent.com/55439979/114273058-35c10900-9a4b-11eb-8558-8c8eaa15eaf9.png)

**Comment by lovelively** [comment]
因为我实在没搞懂这个东西的概念，和实现的方法，麻烦您了

**Comment by xjasonlyu** [comment]
這啥插件，沒用過。你可以試試docker用host模式能不能直接全局好了

**Comment by LeanFly** [comment]
> 您好，能讲解一下这个http代理设置的问题吗，小白实在太难了，我有软路由环境，那个http代理应该如何填呢

如果宿主机的网关走的是软路由，不用配置这个http代理
