### ISSUE TITLE
本地安装失败

### ISSUE THREAD

**Issue by MengChenJack** [xjasonlyu/jellyfin-plugin-avdc#35]
采用本地安装的方式安装
输入此命令：pip3 install -r requirement.txt
提示requirement.txt不存在（将目录下的requirements.txt改名为requirement.txt解决）
接着输入：python3 main.py -p 5000
返回：
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from server import app
  File "/root/avdc-api/server/__init__.py", line 13, in <module>
    import_module('.views', package=__name__)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/root/avdc-api/server/views.py", line 9, in <module>
    from avdc.utility import image
  File "/root/avdc-api/avdc/utility/image.py", line 11, in <module>
    from avdc.utility.imagesize import getSize
  File "/root/avdc-api/avdc/utility/imagesize.py", line 101, in <module>
    def getSize(fileobj) -> tuple[int, int]:
TypeError: 'type' object is not subscriptable

系统：Debian10 buster
python版本：2.7.16
Jellyfin是直接apt安装的，而非使用docker

**Comment by xjasonlyu** [comment]
你到底是什么python版本的，试试python3.9

**Comment by MengChenJack** [comment]
运行此命令发现我的python版本为2.7，我试试能否安装3.9




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xjasonlyu/jellyfin-plugin-avdc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月3日(星期二) 下午2:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xjasonlyu/jellyfin-plugin-avdc] 本地安装失败 (#35)





 
你到底是什么python版本的，试试python3.9
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MengChenJack** [comment]
编译安装Python3.9后，输入python3.9 --version查询版本，可知当前版本为python3.9.1



再次运行：python3 main.py -p 5000


返回结果：



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xjasonlyu/jellyfin-plugin-avdc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月3日(星期二) 下午2:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xjasonlyu/jellyfin-plugin-avdc] 本地安装失败 (#35)





 
你到底是什么python版本的，试试python3.9
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xjasonlyu** [comment]
?

**Comment by MengChenJack** [comment]
是收不到图片吗？
如果我的操作出了问题请大佬指正，您只发一个问号的话，我不懂这是什么意思。
编译安装python以后仍然是同样的报错。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xjasonlyu/jellyfin-plugin-avdc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月3日(星期二) 晚上8:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xjasonlyu/jellyfin-plugin-avdc] 本地安装失败 (#35)





 
?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xjasonlyu** [comment]
没有图片，你应该操作出问题了，你用issue看看。

**Comment by MengChenJack** [comment]
如何使用issue呢？能否给一下详细步骤？
自己去网上搜索的话不能保证结果正确，希望作者大大提供一下详细命令。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xjasonlyu/jellyfin-plugin-avdc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月4日(星期三) 中午11:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xjasonlyu/jellyfin-plugin-avdc] 本地安装失败 (#35)





 
没有图片，你应该操作出问题了，你用issue看看。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xjasonlyu** [comment]
我是说你去Github的Issue就能发图片了。

**Comment by MengChenJack** [comment]
GitHub时断时续




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xjasonlyu/jellyfin-plugin-avdc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月4日(星期三) 晚上11:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xjasonlyu/jellyfin-plugin-avdc] 本地安装失败 (#35)





 
我是说你去Github的Issue就能发图片了。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
