### ISSUE TITLE
Plugin Malfunctioned

### ISSUE THREAD

**Issue by Chaotic-chaos** [xjasonlyu/jellyfin-plugin-avdc#46]
您好，感谢您的辛苦工作。

插件安装成功后显示Malfunctioned，当前环境如下：

- jellyfin: 10.8.0
- os: Debian
- AVDC version: 2021.524.1245.0

jellyfin后台报错如下：
```shell
jellyfin    | [20:48:14] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Jellyfin.Plugin.AVDC.Providers.ActressImageProvider
jellyfin    | System.TypeLoadException: Could not load type 'MediaBrowser.Model.Serialization.IJsonSerializer' from assembly 'MediaBrowser.Model, Version=10.8.0.0, Culture=neutral, PublicKeyToken=null'.
jellyfin    |    at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
jellyfin    |    at System.Reflection.RuntimeConstructorInfo.<get_Signature>g__LazyCreateSignature|19_0()
jellyfin    |    at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
jellyfin    |    at System.Reflection.RuntimeConstructorInfo.GetParameters()
jellyfin    |    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
jellyfin    |    at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
jellyfin    | [20:48:14] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Jellyfin.Plugin.AVDC.Providers.ImageProvider
jellyfin    | System.TypeLoadException: Could not load type 'MediaBrowser.Model.Serialization.IJsonSerializer' from assembly 'MediaBrowser.Model, Version=10.8.0.0, Culture=neutral, PublicKeyToken=null'.
jellyfin    |    at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
jellyfin    |    at System.Reflection.RuntimeConstructorInfo.<get_Signature>g__LazyCreateSignature|19_0()
jellyfin    |    at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
jellyfin    |    at System.Reflection.RuntimeConstructorInfo.GetParameters()
jellyfin    |    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
jellyfin    |    at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
jellyfin    | [20:48:14] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Jellyfin.Plugin.AVDC.Providers.ActressProvider
jellyfin    | System.TypeLoadException: Could not load type 'MediaBrowser.Model.Serialization.IJsonSerializer' from assembly 'MediaBrowser.Model, Version=10.8.0.0, Culture=neutral, PublicKeyToken=null'.
jellyfin    |    at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
jellyfin    |    at System.Reflection.RuntimeConstructorInfo.<get_Signature>g__LazyCreateSignature|19_0()
jellyfin    |    at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
jellyfin    |    at System.Reflection.RuntimeConstructorInfo.GetParameters()
jellyfin    |    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
jellyfin    |    at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
jellyfin    | [20:48:14] [ERR] [1] Emby.Server.Implementations.ApplicationHost: Error creating Jellyfin.Plugin.AVDC.Providers.MovieProvider
jellyfin    | System.TypeLoadException: Could not load type 'MediaBrowser.Model.Serialization.IJsonSerializer' from assembly 'MediaBrowser.Model, Version=10.8.0.0, Culture=neutral, PublicKeyToken=null'.
jellyfin    |    at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
jellyfin    |    at System.Reflection.RuntimeConstructorInfo.<get_Signature>g__LazyCreateSignature|19_0()
jellyfin    |    at System.Reflection.RuntimeConstructorInfo.GetParametersNoCopy()
jellyfin    |    at System.Reflection.RuntimeConstructorInfo.GetParameters()
jellyfin    |    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
jellyfin    |    at Emby.Server.Implementations.ApplicationHost.CreateInstanceSafe(Type type)
```

谢谢！

**Comment by xjasonlyu** [comment]
插件比较长时间没有维护和适配，所以应该是不兼容 jellyfin 10.8.0 版本了。
