### ISSUE TITLE
老哥我是通过docker安装的发现这个错误

### ISSUE THREAD

**Issue by kkh66** [xjasonlyu/jellyfin-plugin-avdc#7]
* Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
[2021-03-31 16:47:02,126] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3080, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3416, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
sqlite3.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3142, in execute_sql
    cursor = self.cursor(commit)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3126, in cursor
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3083, in connect
    self._initialize_connection(self._state.conn)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 2917, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 190, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3080, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3416, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
peewee.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1945, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1993, in try_trigger_before_first_request_functions
    func()
  File "/app/server/views.py", line 16, in _init_database
    sqlite_db_init(app.config.get('DATABASE'))
  File "/app/server/database.py", line 14, in sqlite_db_init
    sqlite_db.create_tables([Metadata, Actress, Cover])
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3332, in create_tables
    model.create_table(**options)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 6672, in create_table
    cls._schema.create_all(safe, **options)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 5783, in create_all
    self.create_table(safe, **table_options)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 5638, in create_table
    self.database.execute(self._create_table(safe=safe, **options))
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3157, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3151, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 2917, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 190, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3142, in execute_sql
    cursor = self.cursor(commit)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3126, in cursor
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3083, in connect
    self._initialize_connection(self._state.conn)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 2917, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 190, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3080, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3416, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
peewee.OperationalError: unable to open database file
42.188.58.171 - - [31/Mar/2021 16:47:02] "GET / HTTP/1.1" 500 -
[2021-03-31 16:47:02,421] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3080, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3416, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
sqlite3.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3142, in execute_sql
    cursor = self.cursor(commit)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3126, in cursor
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3083, in connect
    self._initialize_connection(self._state.conn)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 2917, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 190, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3080, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3416, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
peewee.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1945, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1993, in try_trigger_before_first_request_functions
    func()
  File "/app/server/views.py", line 16, in _init_database
    sqlite_db_init(app.config.get('DATABASE'))
  File "/app/server/database.py", line 14, in sqlite_db_init
    sqlite_db.create_tables([Metadata, Actress, Cover])
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3332, in create_tables
    model.create_table(**options)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 6672, in create_table
    cls._schema.create_all(safe, **options)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 5783, in create_all
    self.create_table(safe, **table_options)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 5638, in create_table
    self.database.execute(self._create_table(safe=safe, **options))
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3157, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3151, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 2917, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 190, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3142, in execute_sql
    cursor = self.cursor(commit)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3126, in cursor
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3083, in connect
    self._initialize_connection(self._state.conn)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 2917, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 190, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3080, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3416, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
peewee.OperationalError: unable to open database file
42.188.58.171 - - [31/Mar/2021 16:47:02] "GET /favicon.ico HTTP/1.1" 500 -
[2021-03-31 17:01:10,287] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3080, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3416, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
sqlite3.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3142, in execute_sql
    cursor = self.cursor(commit)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3126, in cursor
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3083, in connect
    self._initialize_connection(self._state.conn)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 2917, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 190, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3080, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3416, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
peewee.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1945, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1993, in try_trigger_before_first_request_functions
    func()
  File "/app/server/views.py", line 16, in _init_database
    sqlite_db_init(app.config.get('DATABASE'))
  File "/app/server/database.py", line 14, in sqlite_db_init
    sqlite_db.create_tables([Metadata, Actress, Cover])
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3332, in create_tables
    model.create_table(**options)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 6672, in create_table
    cls._schema.create_all(safe, **options)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 5783, in create_all
    self.create_table(safe, **table_options)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 5638, in create_table
    self.database.execute(self._create_table(safe=safe, **options))
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3157, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3151, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 2917, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 190, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3142, in execute_sql
    cursor = self.cursor(commit)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3126, in cursor
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3083, in connect
    self._initialize_connection(self._state.conn)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 2917, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 190, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3080, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3416, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
peewee.OperationalError: unable to open database file
42.188.58.171 - - [31/Mar/2021 17:01:10] "GET / HTTP/1.1" 500 -
[2021-03-31 17:01:10,637] ERROR in app: Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3080, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3416, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
sqlite3.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3142, in execute_sql
    cursor = self.cursor(commit)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3126, in cursor
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3083, in connect
    self._initialize_connection(self._state.conn)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 2917, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 190, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3080, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3416, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
peewee.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1945, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1993, in try_trigger_before_first_request_functions
    func()
  File "/app/server/views.py", line 16, in _init_database
    sqlite_db_init(app.config.get('DATABASE'))
  File "/app/server/database.py", line 14, in sqlite_db_init
    sqlite_db.create_tables([Metadata, Actress, Cover])
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3332, in create_tables
    model.create_table(**options)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 6672, in create_table
    cls._schema.create_all(safe, **options)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 5783, in create_all
    self.create_table(safe, **table_options)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 5638, in create_table
    self.database.execute(self._create_table(safe=safe, **options))
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3157, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3151, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 2917, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 190, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3142, in execute_sql
    cursor = self.cursor(commit)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3126, in cursor
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3083, in connect
    self._initialize_connection(self._state.conn)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 2917, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 190, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3080, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3416, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
peewee.OperationalError: unable to open database file
42.188.58.171 - - [31/Mar/2021 17:01:10] "GET /favicon.ico HTTP/1.1" 500 -
185.202.2.149 - - [31/Mar/2021 19:51:27] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie:')
185.202.2.149 - - [31/Mar/2021 19:51:27] "/*àCookie: mstshash=Administr" HTTPStatus.BAD_REQUEST -
74.120.14.39 - - [01/Apr/2021 02:02:12] code 400, message Bad request version ('?\x14?')
74.120.14.39 - - [01/Apr/2021 02:02:12] "{wV? 
                                             ?b?I??$á??ùN>??|n?/?+????	??" HTTPStatus.BAD_REQUEST -
[2021-04-01 02:02:13,690] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3080, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3416, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
sqlite3.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3142, in execute_sql
    cursor = self.cursor(commit)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3126, in cursor
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3083, in connect
    self._initialize_connection(self._state.conn)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 2917, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 190, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3080, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3416, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
peewee.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1945, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1993, in try_trigger_before_first_request_functions
    func()
  File "/app/server/views.py", line 16, in _init_database
    sqlite_db_init(app.config.get('DATABASE'))
  File "/app/server/database.py", line 14, in sqlite_db_init
    sqlite_db.create_tables([Metadata, Actress, Cover])
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3332, in create_tables
    model.create_table(**options)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 6672, in create_table
    cls._schema.create_all(safe, **options)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 5783, in create_all
    self.create_table(safe, **table_options)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 5638, in create_table
    self.database.execute(self._create_table(safe=safe, **options))
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3157, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3151, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 2917, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 190, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3142, in execute_sql
    cursor = self.cursor(commit)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3126, in cursor
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3083, in connect
    self._initialize_connection(self._state.conn)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 2917, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 190, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3080, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3416, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
peewee.OperationalError: unable to open database file
74.120.14.39 - - [01/Apr/2021 02:02:13] "GET / HTTP/1.1" 500 -
[2021-04-01 02:02:13,985] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3080, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3416, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
sqlite3.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3142, in execute_sql
    cursor = self.cursor(commit)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3126, in cursor
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3083, in connect
    self._initialize_connection(self._state.conn)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 2917, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 190, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3080, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3416, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
peewee.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1945, in full_dispatch_request
    self.try_trigger_before_first_request_functions()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1993, in try_trigger_before_first_request_functions
    func()
  File "/app/server/views.py", line 16, in _init_database
    sqlite_db_init(app.config.get('DATABASE'))
  File "/app/server/database.py", line 14, in sqlite_db_init
    sqlite_db.create_tables([Metadata, Actress, Cover])
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3332, in create_tables
    model.create_table(**options)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 6672, in create_table
    cls._schema.create_all(safe, **options)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 5783, in create_all
    self.create_table(safe, **table_options)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 5638, in create_table
    self.database.execute(self._create_table(safe=safe, **options))
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3157, in execute
    return self.execute_sql(sql, params, commit=commit)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3151, in execute_sql
    self.commit()
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 2917, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 190, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3142, in execute_sql
    cursor = self.cursor(commit)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3126, in cursor
    self.connect()
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3083, in connect
    self._initialize_connection(self._state.conn)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 2917, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 190, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3080, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3416, in _connect
    conn = sqlite3.connect(self.database, timeout=self._timeout,
peewee.OperationalError: unable to open database file
74.120.14.39 - - [01/Apr/2021 02:02:13] "GET / HTTP/1.1" 500 -

**Comment by xjasonlyu** [comment]
你docker的容器配置贴一下。

**Comment by kkh66** [comment]
docker run -d \
    -p 5000:5000 \
    -v $PWD/avdc.db:/avdc.db \
    ghcr.io/xjasonlyu/avdc-api:latest

**Comment by kkh66** [comment]
> 你docker的容器配置贴一下。

发了

**Comment by xjasonlyu** [comment]
迷惑.jpg

你确定本地当前路径是有avdc.db的吗。。

**Comment by kkh66** [comment]
> 迷惑.jpg
> 
> 你确定本地当前路径是有avdc.db的吗。。
我是有看到有avdc.db文件

**Comment by kkh66** [comment]
我用ls来看了下的确是有这个文件不过这个文件没啥东西

**Comment by xjasonlyu** [comment]
你重新下一个avdc.db，然后docker再跑一遍，文件空的就会报错的。

**Comment by kkh66** [comment]
> avdc.d

哦哦

**Comment by kkh66** [comment]
{"message":"unauthorized","status":false} 
变了

**Comment by xjasonlyu** [comment]
你设置了Token就是这样的。

**Comment by kkh66** [comment]
感谢老哥
