### ISSUE TITLE
500错误

### ISSUE THREAD

**Issue by lencshu** [xjasonlyu/jellyfin-plugin-avdc#8]
大佬麻烦看看这个bug是因为什么？
docker里面跑的ghcr.io/xjasonlyu/avdc-api, http访问返回成功`{"message":"AVDC-API","status":true}`

但是实际刮削的时候有错误

jellyfin里面:
~~~
[22:26:11] [INF] [59] Jellyfin.Plugin.AVDC.Providers.MovieProvider: [AVDC] GetMetadata for video: IPX-610
[22:26:12] [ERR] [60] Jellyfin.Plugin.AVDC.Providers.MovieProvider: [AVDC] GetActress for 梓ヒカリ failed: Response status code does not indicate success: 500 (INTERNAL SERVER ERROR).,
[22:26:12] [INF] [60] Jellyfin.Plugin.AVDC.Providers.ImageProvider: [AVDC] GetImages for video: IPX-610,
[22:26:12] [ERR] [61] Jellyfin.Plugin.AVDC.Providers.ImageProvider: [AVDC] GetMetadata for IPX-610 failed: Response status code does not indicate success: 500 (INTERNAL SERVER ERROR).
~~~

avdc-api:
~~~

[2021-04-03 22:26:12,217] ERROR in app: Exception on /actress/梓ヒカリ [GET],
Traceback (most recent call last):,
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3144, in execute_sql,
    cursor.execute(sql, params or ()),
sqlite3.OperationalError: no such table: actresses,
,
During handling of the above exception, another exception occurred:,
,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request,
    rv = self.dispatch_request(),
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request,
    return self.view_functions[rule.endpoint](**req.view_args),
  File "/app/server/views.py", line 59, in _actress,
    actress = api.GetActressByName(name, update=update),
  File "/app/server/api.py", line 152, in GetActressByName,
    actress = db_api.GetActressByName(name),
  File "/app/server/db_api.py", line 32, in GetActressByName,
    result: Actresses = Actresses.get((Actresses.name == name)),
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 6438, in get,
    return sq.get(),
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 6884, in get,
    return clone.execute(database)[0],
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 1907, in inner,
    return method(self, database, *args, **kwargs),
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 1978, in execute,
    return self._execute(database),
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 2150, in _execute,
    cursor = database.execute(self),
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3157, in execute,
    return self.execute_sql(sql, params, commit=commit),
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3151, in execute_sql,
    self.commit(),
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 2917, in __exit__,
    reraise(new_type, new_type(exc_value, *exc_args), traceback),
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 190, in reraise,
    raise value.with_traceback(tb),
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3144, in execute_sql,
    cursor.execute(sql, params or ()),
peewee.OperationalError: no such table: actresses,
10.0.3.3 - - [03/Apr/2021 22:26:12] "GET /actress/梓ヒカリ HTTP/1.1" 500 -,
[2021-04-03 22:26:12,321] ERROR in app: Exception on /metadata/IPX-610 [GET],
Traceback (most recent call last):,
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3144, in execute_sql,
    cursor.execute(sql, params or ()),
sqlite3.OperationalError: no such table: metadata,
,
During handling of the above exception, another exception occurred:,
,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request,
    rv = self.dispatch_request(),
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request,
    return self.view_functions[rule.endpoint](**req.view_args),
  File "/app/server/api.py", line 36, in wrapper,
    return fn(parseVID(vid)[0]),
  File "/app/server/views.py", line 94, in _metadata,
    m = api.GetMetadataByVID(vid, update=update),
  File "/app/server/api.py", line 136, in GetMetadataByVID,
    m = _getLocalMetadata(vid),
  File "/app/server/api.py", line 131, in _getLocalMetadata,
    return db_api.GetMetadataByVID(vid),
  File "/app/server/db_api.py", line 15, in GetMetadataByVID,
    result: Metadata = Metadata.get((Metadata.vid == vid) |,
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 6438, in get,
    return sq.get(),
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 6884, in get,
    return clone.execute(database)[0],
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 1907, in inner,
    return method(self, database, *args, **kwargs),
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 1978, in execute,
    return self._execute(database),
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 2150, in _execute,
    cursor = database.execute(self),
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3157, in execute,
    return self.execute_sql(sql, params, commit=commit),
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3151, in execute_sql,
    self.commit(),
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 2917, in __exit__,
    reraise(new_type, new_type(exc_value, *exc_args), traceback),
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 190, in reraise,
    raise value.with_traceback(tb),
  File "/usr/local/lib/python3.9/site-packages/peewee.py", line 3144, in execute_sql,
    cursor.execute(sql, params or ()),
peewee.OperationalError: no such table: metadata,
~~~

avdc.db我打开看了，metadata和actresses这俩表都是存在的，所以为啥会返回500错误？

**Comment by xjasonlyu** [comment]
我的锅，昨天加了个in memory database，默认用了memory sqlite。

你加一个环境变量`AVDC_DBURL=sqlite:///avdc.db`试试

**Comment by lencshu** [comment]
ok，加上就通了
